export interface Facility {
  id: string
  name: string
  type: string
  address: string
  phone: string
  currentWaitTime: number
  queueLength: number
  isOpen: boolean
  hoursToday: string
  hours: {
    monday: string
    tuesday: string
    wednesday: string
    thursday: string
    friday: string
    saturday: string
    sunday: string
  }
  services: string[]
}

export const facilities: Facility[] = [
  {
    id: "regina-ucc",
    name: "Regina Urgent Care Centre",
    type: "Urgent Care",
    address: "1320 Albert Street, Regina, SK S4R 2R1",
    phone: "(306) 766-4444",
    currentWaitTime: 45,
    queueLength: 12,
    isOpen: true,
    hoursToday: "8:00 AM - 9:30 PM",
    hours: {
      monday: "8:00 AM - 9:30 PM",
      tuesday: "8:00 AM - 9:30 PM",
      wednesday: "8:00 AM - 9:30 PM",
      thursday: "8:00 AM - 9:30 PM",
      friday: "8:00 AM - 9:30 PM",
      saturday: "8:00 AM - 9:30 PM",
      sunday: "8:00 AM - 9:30 PM",
    },
    services: ["Minor Injuries", "Illness Treatment", "X-rays", "Lab Tests", "Prescriptions"],
  },
  {
    id: "albert-parliament",
    name: "Albert & Parliament Primary Health Care Centre",
    type: "Walk-in Clinic",
    address: "3992 Albert Street, Regina, SK S4S 3R1",
    phone: "(306) 757-0303",
    currentWaitTime: 25,
    queueLength: 6,
    isOpen: true,
    hoursToday: "8:00 AM - 8:00 PM",
    hours: {
      monday: "8:00 AM - 8:00 PM",
      tuesday: "8:00 AM - 8:00 PM",
      wednesday: "8:00 AM - 8:00 PM",
      thursday: "8:00 AM - 8:00 PM",
      friday: "8:00 AM - 8:00 PM",
      saturday: "9:00 AM - 5:00 PM",
      sunday: "10:00 AM - 4:00 PM",
    },
    services: [
      "General Practice",
      "Walk-in Appointments",
      "Immunizations",
      "Health Assessments",
      "Chronic Disease Management",
    ],
  },
  {
    id: "core-medicenter",
    name: "Core Medicenter",
    type: "Walk-in Clinic",
    address: "1635 11th Avenue, Regina, SK S4P 0H5",
    phone: "(306) 584-8880",
    currentWaitTime: 35,
    queueLength: 8,
    isOpen: true,
    hoursToday: "9:00 AM - 6:00 PM",
    hours: {
      monday: "9:00 AM - 6:00 PM",
      tuesday: "9:00 AM - 6:00 PM",
      wednesday: "9:00 AM - 6:00 PM",
      thursday: "9:00 AM - 6:00 PM",
      friday: "9:00 AM - 6:00 PM",
      saturday: "10:00 AM - 2:00 PM",
      sunday: "Closed",
    },
    services: ["Walk-in Care", "Family Medicine", "Minor Procedures", "Travel Medicine", "Sports Medicine"],
  },
  {
    id: "dr-patel",
    name: "Dr. Patel's Medical Clinic",
    type: "Walk-in Clinic",
    address: "2625 Dewdney Avenue, Regina, SK S4T 0X4",
    phone: "(306) 352-3454",
    currentWaitTime: 20,
    queueLength: 4,
    isOpen: true,
    hoursToday: "8:30 AM - 7:00 PM",
    hours: {
      monday: "8:30 AM - 7:00 PM",
      tuesday: "8:30 AM - 7:00 PM",
      wednesday: "8:30 AM - 7:00 PM",
      thursday: "8:30 AM - 7:00 PM",
      friday: "8:30 AM - 7:00 PM",
      saturday: "9:00 AM - 3:00 PM",
      sunday: "Closed",
    },
    services: ["General Practice", "Pediatric Care", "Women's Health", "Preventive Care", "Chronic Disease Management"],
  },
  {
    id: "fifth-avenue",
    name: "Fifth Avenue Medical Clinic",
    type: "Walk-in Clinic",
    address: "3013 Fifth Avenue, Regina, SK S4T 0L6",
    phone: "(306) 757-2664",
    currentWaitTime: 55,
    queueLength: 15,
    isOpen: true,
    hoursToday: "8:00 AM - 8:00 PM",
    hours: {
      monday: "8:00 AM - 8:00 PM",
      tuesday: "8:00 AM - 8:00 PM",
      wednesday: "8:00 AM - 8:00 PM",
      thursday: "8:00 AM - 8:00 PM",
      friday: "8:00 AM - 8:00 PM",
      saturday: "9:00 AM - 5:00 PM",
      sunday: "10:00 AM - 4:00 PM",
    },
    services: ["Walk-in Services", "Family Medicine", "Lab Services", "Prescriptions", "Health Screenings"],
  },
  {
    id: "regina-general",
    name: "Regina General Hospital",
    type: "Hospital",
    address: "1440 14th Avenue, Regina, SK S4P 0W5",
    phone: "(306) 766-4444",
    currentWaitTime: 120,
    queueLength: 28,
    isOpen: true,
    hoursToday: "Open 24 Hours",
    hours: {
      monday: "Open 24 Hours",
      tuesday: "Open 24 Hours",
      wednesday: "Open 24 Hours",
      thursday: "Open 24 Hours",
      friday: "Open 24 Hours",
      saturday: "Open 24 Hours",
      sunday: "Open 24 Hours",
    },
    services: [
      "Emergency Care",
      "Trauma Services",
      "Surgery",
      "Intensive Care",
      "Diagnostic Imaging",
      "Laboratory Services",
    ],
  },
  {
    id: "pasqua-hospital",
    name: "Pasqua Hospital",
    type: "Hospital",
    address: "4101 Dewdney Avenue, Regina, SK S4T 7T1",
    phone: "(306) 766-2222",
    currentWaitTime: 95,
    queueLength: 22,
    isOpen: true,
    hoursToday: "Open 24 Hours",
    hours: {
      monday: "Open 24 Hours",
      tuesday: "Open 24 Hours",
      wednesday: "Open 24 Hours",
      thursday: "Open 24 Hours",
      friday: "Open 24 Hours",
      saturday: "Open 24 Hours",
      sunday: "Open 24 Hours",
    },
    services: [
      "Emergency Care",
      "Cardiac Care",
      "Renal Services",
      "Mental Health",
      "Rehabilitation",
      "Palliative Care",
    ],
  },
  {
    id: "northgate-medical",
    name: "Northgate Medical Clinic",
    type: "Walk-in Clinic",
    address: "3939 Rochdale Boulevard, Regina, SK S4X 4P7",
    phone: "(306) 789-2900",
    currentWaitTime: 30,
    queueLength: 7,
    isOpen: true,
    hoursToday: "8:00 AM - 8:00 PM",
    hours: {
      monday: "8:00 AM - 8:00 PM",
      tuesday: "8:00 AM - 8:00 PM",
      wednesday: "8:00 AM - 8:00 PM",
      thursday: "8:00 AM - 8:00 PM",
      friday: "8:00 AM - 8:00 PM",
      saturday: "9:00 AM - 5:00 PM",
      sunday: "10:00 AM - 4:00 PM",
    },
    services: ["Walk-in Care", "Family Practice", "Minor Injuries", "Vaccinations", "Physical Exams"],
  },
  {
    id: "southland-medical",
    name: "Southland Medical Clinic",
    type: "Walk-in Clinic",
    address: "2965 Gordon Road, Regina, SK S4S 6H7",
    phone: "(306) 586-0011",
    currentWaitTime: 40,
    queueLength: 10,
    isOpen: true,
    hoursToday: "8:00 AM - 6:00 PM",
    hours: {
      monday: "8:00 AM - 6:00 PM",
      tuesday: "8:00 AM - 6:00 PM",
      wednesday: "8:00 AM - 6:00 PM",
      thursday: "8:00 AM - 6:00 PM",
      friday: "8:00 AM - 6:00 PM",
      saturday: "9:00 AM - 1:00 PM",
      sunday: "Closed",
    },
    services: [
      "General Practice",
      "Walk-in Services",
      "Chronic Disease Care",
      "Preventive Medicine",
      "Minor Procedures",
    ],
  },
]
